### ISSUE TITLE
Profile Object detached from state

### ISSUE THREAD

**Issue by patrozada** [Adalab/f-m3-codebusters#27]
Hi @carmen-tm,
I have just pulled dev and I have realized there is a problem with profileObject that prevents the rendering of the card generator page.
For some reason it does not appear to be sent via props from CardGenerator to FillPanel, so when it tries to use it there it is undefined, can you please take a look just in case this is not the reason?

Let me know if I can help

**Comment by carmen-tm** [comment]
Done!! 
Some props were missed on the way as you suggested. 
Fixed and done! :D
